version: "3.9"
services:
  frontend:
    build: ./frontend
    command: npm run dev
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000" # optional direct access
    networks: [yapnet]
    depends_on: [nginx]

  backend:
    build: ./backend
    command: npm run dev
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4000
    expose:
      - "4000"
    ports:
      - "4000:4000" # optional direct access
    networks: [yapnet]

  nginx:
    image: nginx:1.27
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - yapnet

networks:
  yapnet:
